/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarBadge: typeof import('./components/AvatarBadge.vue')['default']
    BackToBlogButton: typeof import('./components/BackToBlogButton.vue')['default']
    BackToHomeButton: typeof import('./components/BackToHomeButton.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    ControlPanel: typeof import('./components/ControlPanel.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    GlassBreadcrumb: typeof import('./components/GlassBreadcrumb.vue')['default']
    GlobalSearch: typeof import('./components/GlobalSearch.vue')['default']
    HitokotoCard: typeof import('./components/HitokotoCard.vue')['default']
    HomeHero: typeof import('./components/home/HomeHero.vue')['default']
    HomeWorksSection: typeof import('./components/home/HomeWorksSection.vue')['default']
    MarkdownView: typeof import('./components/MarkdownView.vue')['default']
    Mascot: typeof import('./components/Mascot.vue')['default']
    MoyuBackToHubButton: typeof import('./components/moyu/MoyuBackToHubButton.vue')['default']
    MoyuGameEmbed: typeof import('./components/moyu/MoyuGameEmbed.vue')['default']
    MoyuGameShell: typeof import('./components/moyu/MoyuGameShell.vue')['default']
    MoyuTopBar: typeof import('./components/moyu/MoyuTopBar.vue')['default']
    MusicPlayer: typeof import('./components/MusicPlayer.vue')['default']
    NewsletterSignup: typeof import('./components/NewsletterSignup.vue')['default']
    PlayArea: typeof import('./components/PlayArea.vue')['default']
    PlayerHand: typeof import('./components/PlayerHand.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteBackgroundVideos: typeof import('./components/site/SiteBackgroundVideos.vue')['default']
    SiteBackToTop: typeof import('./components/site/SiteBackToTop.vue')['default']
    SiteGlassFooter: typeof import('./components/site/SiteGlassFooter.vue')['default']
    SiteTopNav: typeof import('./components/site/SiteTopNav.vue')['default']
    ToolBackBar: typeof import('./components/tools/ToolBackBar.vue')['default']
    ToolBase64Codec: typeof import('./components/tools/ToolBase64Codec.vue')['default']
    ToolCpsTest: typeof import('./components/tools/ToolCpsTest.vue')['default']
    ToolModuleIcon: typeof import('./components/tools/ToolModuleIcon.vue')['default']
    ToolPageShell: typeof import('./components/tools/ToolPageShell.vue')['default']
    ToolPasswordGen: typeof import('./components/tools/ToolPasswordGen.vue')['default']
    ToolPomodoro: typeof import('./components/tools/ToolPomodoro.vue')['default']
    ToolReactionTest: typeof import('./components/tools/ToolReactionTest.vue')['default']
    ToolSchulteTest: typeof import('./components/tools/ToolSchulteTest.vue')['default']
    WallComposer: typeof import('./components/home/wall/WallComposer.vue')['default']
    WallList: typeof import('./components/home/wall/WallList.vue')['default']
    WallPager: typeof import('./components/home/wall/WallPager.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
